# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'
end
